Avradip24/Code_Wizards

source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI.sln
source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/Program.cs
source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/ProjectNeoCortexAPI.csproj

Project Folder Creation

---

source/MySEProject/InitialProjectPlan.md

Adding Problem Statement and Development Plan

Creating InitialProjectPlan

---

source/MySEProject/InitialProjectPlan.md

Completing project workflow and uploading project pipeline.

Updating InitialProjectPlan

---

source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/Program.cs

Updating the program file and adding the folder path

---

source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/ImageBinarizer.cs
source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/Program.cs
source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/ProjectNeoCortexAPI.csproj

Adding the Image Binarizer

---

source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/BitmapExtension.cs
source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/ImageBinarizer.cs
source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/ImagePixelsDataHandler.cs
source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/Program.cs

Please merge the code of ImageBinarizer

Adding ImageBinarizer and calling it from the program file

---

source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/Program.cs

Updating the program file to binarize multiple images

---

source/MySEProject/README.md

Updating the README File

---

source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/Program.cs

Adding the functionality to take Images of various extension and storing the output to a specific folder

---

source/MySEProject/ProjectNeoCortexAPI/ProjectNeoCortexAPI/SpatialPatternLearning.cs

Adding Spatial Pooler code

---

source/NeoCortexUtils/NeoCortexUtils.cs
source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Fixing the aspect ratio of the binarized image

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

updated the functionality to binarize all the images at once before the training cycle 

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Adding the functionality to delete and recreate the BinarizedImages folder

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Adding changes to take 5 stable cycles before break and adding Debug Lines

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Creating a text file and storing all the cycle SDR in that file

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Storing the SDR after stability is reached

Storing the SDR after stability is reached

---

source/MySEProject/README.md

Methodology of HTM Classifier

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Adding the functionaly of images prediction in the HTM Classifiers

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Adding the functionality of Image Prediction in HTM Classifier

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Mapping the Binarized Images with the Actual Images for Similarity Check

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Adding the functionality of Image Prediction in KNN Classifier

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Calling the image reconstruction function and storing them in separate output folder

---

source/Samples/NeoCortexApiSample/knnClassifier.cs

Adding KNN Classifier with IClassifier interface

---

source/Samples/NeoCortexApiSample/IClassifier.cs

Updating IClassifier instance

---

source/NeoCortexApi/Classifiers/KnnClassifier.cs

Removing previously added changes which are not needed in KNNClassifier.cs

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Reconstructing Images by taking SDR from Classifiers

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs

Setting Stopwatch for Spatial Pooler and Classifier

---

source/Samples/NeoCortexApiSample/ImageBinarizerSpatialPattern.cs
source/Samples/NeoCortexApiSample/ImageReconstructor.cs

Assigning the newly created binarized images one for testing and one for training
